//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swerea_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstantParameters
    {
        public int ConstID { get; set; }
        public double PrinterCost { get; set; }
        public double MaterialCost { get; set; }
        public double LabourCost { get; set; }
        public double PreProcessingTime { get; set; }
        public double SetupTime { get; set; }
        public double PowderHandlingTime { get; set; }
        public double JobStartTime { get; set; }
        public double BuildRemovalTime { get; set; }
        public double PartRemovalTime { get; set; }
        public double PostProcessingTime { get; set; }
        public double MachineCleaningTime { get; set; }
    }
}
