//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swerea_API.Models
{
    using System;
    using System.Collections.Generic;

    public class CostEstimation
    {
        public int BuildId { get; set; }
        public string StlFileName { get; set; }
        public int NumberOfLayers { get; set; }
        public double TotalZheight { get; set; }
        public int PrintingTime { get; set; }
        public int CostEstimate { get; set; }
        public int TotalPowderUsed { get; set; }
        public CostEstimation() { }

        public CostEstimation(int buildId, string stlFileName, double totalZheight, int numberOfLayers, int printingTime, int costEstimate, int totalPowderUsed)
        {
            BuildId = buildId;
            StlFileName = stlFileName;
            TotalZheight = totalZheight;
            NumberOfLayers = numberOfLayers;
            PrintingTime = printingTime;
            TotalPowderUsed = totalPowderUsed;
            CostEstimate = costEstimate;
        }

        public CostEstimation(int buildId, string stlFileName, int numberOfLayers, int printingTime, int costEstimate, int totalPowderUsed)
        {
            BuildId = buildId;
            StlFileName = stlFileName;
            NumberOfLayers = numberOfLayers;
            PrintingTime = printingTime;
            TotalPowderUsed = totalPowderUsed;
            CostEstimate = costEstimate;
        }

    }
}