//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swerea_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimatedValues
    {
        public int ValueID { get; set; }
        public double TotalPowderUsed { get; set; }
        public double TotalPrintingTime { get; set; }
        public double TotalCost { get; set; }
        public int BuildId { get; set; }
    
        public virtual Build Build { get; set; }
    }
}
