//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swerea_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralTest
    {
        public Nullable<bool> SupportRemoval { get; set; }
        public Nullable<bool> WEDM { get; set; }
        public string WEDMComments { get; set; }
        public Nullable<bool> Blasting { get; set; }
        public string BlastingComments { get; set; }
        public int GeneralID { get; set; }
        public string QRCode { get; set; }
        public Nullable<int> PartId { get; set; }
    }
}
