//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swerea_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialPdf
    {
        public int MaterialPdfID { get; set; }
        public string FileName { get; set; }
        public Nullable<int> MaterialId { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
