//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swerea_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartTestDetails
    {
        public int PartTestDetailsID { get; set; }
        public Nullable<int> PartId { get; set; }
        public Nullable<int> PartTestId { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual PartTest PartTest { get; set; }
    }
}
