//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swerea_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintingInfo
    {
        public int PrintingInfoID { get; set; }
        public string BuildStatus { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> PrintingDate { get; set; }
        public string Operator { get; set; }
        public string TypeOfmachine { get; set; }
        public Nullable<double> PowderWeightStart { get; set; }
        public Nullable<double> PowderweightEnd { get; set; }
        public Nullable<double> WeightPowderWaste { get; set; }
        public Nullable<double> PowerUsed { get; set; }
        public string PlatformMaterial { get; set; }
        public Nullable<double> PlatformWeight { get; set; }
        public string PrintedTime { get; set; }
        public string PowderCondition { get; set; }
        public Nullable<int> NumberLayers { get; set; }
        public Nullable<double> DPCFactor { get; set; }
        public string MinExposureTime { get; set; }
        public string Comments { get; set; }
        public int BuildId { get; set; }
    
        public virtual Build Build { get; set; }
    }
}
