//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swerea_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StressRelieveingTest
    {
        public int StressRelieveingTestID { get; set; }
        public bool ShieldingGas { get; set; }
        public int PartTestId { get; set; }
    
        public virtual PartTest PartTest { get; set; }
    }
}
