//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swerea_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableParameters
    {
        public int ParamID { get; set; }
        public string MaterialType { get; set; }
        public double Volume { get; set; }
        public double Weight { get; set; }
        public double ZHeight { get; set; }
        public int NumberOfLayers { get; set; }
        public string UnitOfLength { get; set; }
        public double InfillPercentage { get; set; }
        public string FileName { get; set; }
        public int BuildId { get; set; }
    
        public virtual Build Build { get; set; }
    }
}
